services:
  postgres:
    container_name: webler-codes-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_codes_localhost_db
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: webler-codes-pgadmin
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@weblercodes.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=50
      - GUNICORN_ACCESS_LOGFILE=/dev/null
    volumes:
      - ./.docker/pgadmin/config/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"

  backend:
    container_name: webler-codes-backend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  nginx:
    container_name: webler-codes-nginx
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-nginx
    depends_on:
      - backend
    env_file:
      - ./backend/.env.development
    volumes:
      - .:/var/www/webler-codes:ro
    ports:
      - "443:443"
      - "80:80"
  
  postgres-test:
    container_name: webler-codes-postgres-test
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_codes_localhost_test_db
    ports:
      - "5433:5432"

  redis:
    container_name: webler-codes-redis
    image: redis:alpine
    ports:
      - "6379:6379"
  dind:
    container_name: webler-codes-dind
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-dind
    environment:
      - AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8b/e751r2lhyMNIJU/L3U7dQh66dCzitgEOz6cOd/fUuIMjvQ1KnnR8+FIijMpGEwKvIN/ejb3uCwVJbtD7kgXYuN0IAcgyCamks2UBchjVveXCJndsDdqMyhgQbTouKHugsgjUX+5tEc2dr7W/xVXUpo3q2soDhALfu2KyfRzq7EYmBFf53OJ7dljGoytbRP+Wz+A9nzoHjsq2Qc9A/RX1ZnWr+05f/0gD+C2yNCpUpRzUCUxCrXZUIqNR8fv1YNX19+8T0Ke/KR8Gr+mCMDAk1dwhOdbssQm1Idwa/bc6yYmhNSt0c9UO4pJFr1h6yEOrqCMfz/KJdPviTAp7PGUe2DsDw7Zu4RjVhTCNALNNwkrZYnw1fBr6kFrAmVvLSFu2O2z77a0q5Wd9dLfzB1l181FB1jVF8RkC3bw+U/qHKe4seOlqHG996G2CQ5AcCcP+dqg9uZFQ3FRaKKR+4i5cMD91JJFHYKMQT2pYVFVcOHATwccs1NDwy65CrDMAE= kira@Albion
    privileged: true
    ports:
      - "10022:22"