services:
  postgres:
    container_name: webler-codes-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_codes_localhost_db
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: webler-codes-pgadmin
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@weblercodes.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=50
      - GUNICORN_ACCESS_LOGFILE=/dev/null
    volumes:
      - ./.docker/pgadmin/config/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"

  backend:
    container_name: webler-codes-backend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/package.json:/var/www/webler-codes/backend/package.json:ro
      - ./backend/src:/var/www/webler-codes/backend/src:ro
      - ./backend/.env:/var/www/webler-codes/backend/.env:ro
      - ./backend/prisma/schema.prisma:/var/www/webler-codes/backend/prisma/schema.prisma:ro
  
  nginx:
    container_name: webler-codes-nginx
    image: nginx:1.27-alpine
    depends_on:
      - backend
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend/dist:/var/www/webler-codes/frontend/dist:ro
      - ./.docker/nginx/certs/server.crt:/etc/nginx/server.crt:ro
      - ./.docker/nginx/certs/server.key:/etc/nginx/server.key:ro
      - ./.docker/nginx/config/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "443:443"
      - "80:80"
    
