services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_localhost_db
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-backend
    environment:
      NODE_ENV: development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/package.json:/var/www/webler-codes/backend/package.json
      - ./backend/src:/var/www/webler-codes/backend/src
      - ./backend/prisma:/var/www/webler-codes/backend/prisma
      - ./backend/.env:/var/www/webler-codes/backend/.env
      - ./backend/logs:/var/www/webler-codes/backend/logs
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - backend
    volumes:
      - ./:/var/www/webler-codes:ro
      - ./.docker/config/nginx/httpd_default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/certs/server.crt:/etc/nginx/server.crt:ro
      - ./.docker/certs/server.key:/etc/nginx/server.key:ro
    ports:
      - "443:443"
      - "80:80"
    
