services:
  postgres:
    container_name: webler-codes-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_codes_localhost_db
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: webler-codes-pgadmin
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@weblercodes.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=50
      - GUNICORN_ACCESS_LOGFILE=/dev/null
    volumes:
      - ./.docker/pgadmin/config/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"

  backend:
    container_name: webler-codes-backend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  nginx:
    container_name: webler-codes-nginx
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-nginx
    depends_on:
      - backend
    env_file:
      - ./backend/.env.development
    volumes:
      - .:/var/www/webler-codes:ro
      - ./.docker/nginx/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
      - "80:80"
  
  postgres-test:
    container_name: webler-codes-postgres-test
    image: postgres:16
    environment:
      - POSTGRES_USER=webler_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webler_codes_localhost_test_db
    ports:
      - "5433:5432"

  redis:
    container_name: webler-codes-redis
    image: redis:alpine
    ports:
      - "6379:6379"

  dind:
    container_name: webler-codes-dind
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-dind
    privileged: true
    ports:
      - "10022:22"