FROM docker:27.1.1-dind-alpine3.20

RUN apk add --no-cache \ 
    openssh

RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
	echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

COPY ./.docker/dind/entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD []