FROM node:20-alpine

WORKDIR /var/www/webler-codes/backend

COPY ./backend/package.json ./package.json
COPY ./backend/prisma/schema.prisma ./prisma/schema.prisma

RUN npm install
RUN npx prisma generate

EXPOSE ${BACKEND_PORT}

CMD ["npm", "run", "dev"]